---
title: "Data Import"
output: github_document
---

```{r setup}
library(tidyverse)
```
## Read in some Data

Read in the litters dataset.

```{r}
litters_df <- read_csv("./data/FAS_litters.csv") 
# Follow up Steps
litters_df <- janitor::clean_names(litters_df)
```    
## Take a look at the data
Printing in the console.

```{r}
litters_df
head(litters_df)
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```

## Options to read_csv

Check out `?read_csv()` for more information.
```{r}
litters_df <- read_csv("./data/FAS_litters.csv", skip = 10, col_names = FALSE)

#when csv structure is strange: the first row is not variable names

litters_df <- read_csv("./data/FAS_litters.csv", na = c("", ".", 999))

litters_df <- read_csv("./data/FAS_litters.csv", col_types = )
```

## Other file formats

Read in an excel file.
Check ?read_excel

```{r}
library(readxl)
mlb_df <- read_excel("./data/mlb11.xlsx")
mlb_df
mlb_df <- read_excel("./data/mlb11.xlsx", range = "A1:F7")
mlb_df
```

Read in a SAS file.

```{r}
library(haven)
pulse_df <- read_sas("./data/public_pulse_data.sas7bdat") 
head(pulse_df)
```

## Comparison with Base R

what about `read.csv` ...?

```{r}
litters_base <- read.csv("./data/FAS_litters.csv")
litters_readr <- read_csv("./data/FAS_litters.csv")

head(litters_base)
head(litters_readr)
```

## Export Data

Export the mlb sub-table.

```{r}
write_csv(mlb_df, "./data/mlb_subtable.csv")
```